@startuml
start

:"Введите название товара";
:Считывание названия товара;
:Поиск товара в базе данных;
if (Товар найден?) then (да)
    if (Требуется рецепт?) then (да)
        :"Необходим рецепт от врача.";
    else(Нет)
        :Рецепт не требуется.;
    endif
else(нет)
    :"Такого товара нет";
endif
stop
@enduml