@startuml
start
:"Введите данные о товаре";
:Считывание названия, количества,
необходимость рецепта от врача;

:Переход к новой полке;
if (Есть ли свободные полки?) then (да)
  :"Свободных полок нет";
else (нет)
    repeat
    :Переход к новой полке;
        ->Нет;
    repeat while (Хватит места на полке, чтобы уместить товар?) is (Нет) not (Да)
    :Занесение значений в базу данных;
endif
stop
@enduml