@startuml
start

:"Введите название товара";
:Считывание названия товара;

if (Пользователь продавец?) then (да)
    :Поиск товара в базе данных;
    if (Количество товара не равно 0?) then (да)
        if (Нужен рецепт от врача?) then (да)
        :"Товар в наличии. Необходим рецепт от врача.
         Расположение товара: " (номер полки товара)";
        else(нет)
        :"Товар в наличии.
         Расположение товара:" (номер полки товара);
         endif
    else(Нет)
    :"Товара нет в наличии";
    endif
else(Нет)
:Поиск товара в базе данных;
    if (Количество товара не равно 0?) then (да)
        if (Нужен рецепт от врача?) then (да)
        :"Товар в наличии. Необходим рецепт от врача.";
        else(нет)
        :"Товар в наличии.;
         endif
    else(Нет)
    :"Товара нет в наличии";
    endif


endif
stop
@enduml